TRAIN_DATA_FOLDER: '../../data/processed_train'
TRAIN_DATA_LIST_FILE: '../../data/processed_train_file_name_list.txt'
VAL_DATA_FOLDER: '../../data/processed_val'
VAL_DATA_LIST_FILE: '../../data/processed_val_file_name_list.txt'